image: node:9.11.2

pipelines:
    branches:

        feature/*:
            - step:
                name: Test
                script:
                   - git submodule update --init --remote
                   - export EDITION=suggest_demo
                   - npm install -g npm
                   - npm ci
                   - npm test
            - step:
                name: Deploy to TEST
                deployment: test
                trigger: manual
                script:
                    - export APP=fdd.api
                    - export REMOTE=ubuntu@18.195.153.27
                    - export HOST_DIR=/var/www/hosts/fdd-test-api
                    - ./deploy.sh

            - step:
                name: Deploy demo to TEST
                trigger: manual
                script:
                    - export EDITION=demo
                    - export APP=fdd.demo.api
                    - export REMOTE=ubuntu@18.195.153.27
                    - export HOST_DIR=/var/www/hosts/fdd-test-demo-api
                    - ./deploy.sh

        hotfix/*:
            - step:
                name: Test
                script:
                    - git submodule update --init --remote
                    - npm install -g npm
                    - npm ci
                    - npm test
            - step:
                name: Deploy to TEST
                deployment: test
                trigger: manual
                script:
                    - export APP=fdd.api
                    - export REMOTE=ubuntu@18.195.153.27
                    - export HOST_DIR=/var/www/hosts/fdd-test-api
                    - ./deploy.sh

            - step:
                name: Deploy demo to TEST
                trigger: manual
                script:
                    - export APP=fdd.demo.api
                    - export REMOTE=ubuntu@18.195.153.27
                    - export HOST_DIR=/var/www/hosts/fdd-test-demo-api
                    - ./deploy.sh

        develop:
            - step:
                name: Test
                script:
                    - git submodule update --init --remote
                    - npm install -g npm
                    - npm ci
                    - npm test
            - step:
                name: Deploy to TEST
                deployment: test
                trigger: manual
                script:
                    - git submodule update --init --remote
                    - export APP=fdd.api
                    - export REMOTE=ubuntu@18.195.153.27
                    - export HOST_DIR=/var/www/hosts/fdd-test-api
                    - ./deploy.sh
            - step:
                name: Deploy demo to TEST
                trigger: manual
                script:
                    - export APP=fdd.demo.api
                    - export REMOTE=ubuntu@18.195.153.27
                    - export HOST_DIR=/var/www/hosts/fdd-test-demo-api
                    - ./deploy.sh

        release/*:
            - step:
                name: Test
                script:
                    - git submodule update --init --remote
                    #- ./bumpversion.sh
                    - npm install -g npm
                    - npm ci
                    - npm test
            - step:
                name: Deploy to STAGING
                deployment: staging
                trigger: manual
                script:
                    - export APP=fdd.api
                    - export REMOTE=ubuntu@52.57.66.206
                    - export HOST_DIR=/var/www/hosts/fdd-staging-api
                    - ./deploy.sh
            - step:
                name: Deploy demo to STAGING
                trigger: manual
                script:
                    - export APP=fdd.demo.api
                    - export REMOTE=ubuntu@52.57.66.206
                    - export HOST_DIR=/var/www/hosts/fdd-staging-demo-api
                    - ./deploy.sh
            - step:
                name: Deploy mainnet to STAGING
                trigger: manual
                script:
                    - export APP=fdd.mainnet.api
                    - export REMOTE=ubuntu@52.57.66.206
                    - export HOST_DIR=/var/www/hosts/fdd-staging-mainnet-api
                    - ./deploy.sh

        master:
            - step:
                name: Test
                script:
                    - git submodule update --init --remote
                    - echo Test
            - step:
                name: Deploy CFFDD to PRODUCTION
                trigger: manual
                script:
                     - export APP=cffdd.api
                     - export REMOTE=ubuntu@18.195.133.38
                     - export HOST_DIR=/var/www/hosts/cf-api
                     - git submodule update --init --remote
                     - cd ./src/config && git checkout cffdd && cd ../..
                     - ./deploy.sh
            - step:
                name: Deploy demo to PRODUCTION
                trigger: manual
                script:
                     - export APP=fdd.demo.api
                     - export REMOTE=ubuntu@18.195.133.38
                     - export HOST_DIR=/var/www/hosts/fdd-demo-api
                     - ./deploy.sh
            - step:
                name: Deploy to PRODUCTION
                deployment: production
                trigger: manual
                script:
                     - export APP=fdd.api
                     - export REMOTE=ubuntu@18.195.133.38
                     - export HOST_DIR=/var/www/hosts/fdd-api
                     - ./deploy.sh

    custom:
        deploy-test:
            - step:
                name: Test
                script:
                    - echo Test
            - step:
                name: Deploy to TEST
                deployment: test
                trigger: manual
                script:
                    - export APP=fdd.api
                    - export REMOTE=ubuntu@18.195.153.27
                    - export HOST_DIR=/var/www/hosts/fdd-test-api
                    - git submodule update --init --remote
                    - cd ./src/config && git checkout master && cd ../..
                    - ./deploy.sh
        deploy-test-demo:
            - step:
                name: Test
                script:
                    - echo Test
            - step:
                name: Deploy Demo to TEST (CF)
                deployment: test
                trigger: manual
                script:
                    - export APP=fdd.demo.api
                    - export REMOTE=ubuntu@18.195.153.27
                    - export HOST_DIR=/var/www/hosts/fdd-test-demo-api
                    - git submodule update --init --remote
                    - cd ./src/config && git checkout cffdd && cd ../..
                    - ./deploy.sh

        deploy-staging:
            - step:
                name: Test
                script:
                    - git submodule update --init --remote
                    #- ./bumpversion.sh
                    - npm install -g npm
                    - npm ci
                    - npm test
            - step:
                name: Deploy to STAGING
                trigger: manual
                script:
                    - export APP=fdd.api
                    - export REMOTE=ubuntu@52.57.66.206
                    - export HOST_DIR=/var/www/hosts/fdd-staging-api
                    - git submodule update --init --remote
                    - cd ./src/config && git checkout master && cd ../..
                    - ./deploy.sh
        deploy-staging-demo:
            - step:
                name: Test
                script:
                    #- ./bumpversion.sh
                    - npm install -g npm
                    - npm ci
                    - npm test
            - step:
                name: Deploy demo to STAGING
                trigger: manual
                script:
                    - export APP=fdd.demo.api
                    - export REMOTE=ubuntu@52.57.66.206
                    - export HOST_DIR=/var/www/hosts/fdd-staging-demo-api
                    - ./deploy.sh
        deploy-staging-mainnet:
            - step:
                name: Test
                script:
                    #- ./bumpversion.sh
                    - npm install -g npm
                    - npm ci
                    - npm test
            - step:
                name: Deploy mainnet to STAGING
                trigger: manual
                script:
                    - export APP=fdd.mainnet.api
                    - export REMOTE=ubuntu@52.57.66.206
                    - export HOST_DIR=/var/www/hosts/fdd-staging-mainnet-api
                    - ./deploy.sh
        deploy-tokensummit-to-test:
            - step:
                name: Test
                script:
                    - echo Test
            - step:
                name: Deploy TS to TEST
                deployment: test
                trigger: manual
                script:
                    - export APP=fdd.api
                    - export REMOTE=ubuntu@18.195.153.27
                    - export HOST_DIR=/var/www/hosts/fdd-test-api
                    - git submodule update --init --remote
                    - cd ./src/config && git checkout tokensummit && cd ../..
                    - ./deploy.sh

        deploy-production:
            - step:
                name: Test
                script:
                    - echo Test
            - step:
                name: To PRODUCTION
                deployment: test
                trigger: manual
                script:
                    - export APP=fdd.api
                    - export REMOTE=ubuntu@18.195.133.38
                    - export HOST_DIR=/var/www/hosts/fdd-api
                    - git submodule update --init --remote
                    - cd ./src/config && git checkout master && cd ../..
                    - ./deploy.sh

        deploy-production-demo:
            - step:
                name: Test
                script:
                    - git submodule update --init --remote
                    - echo Test
            - step:
                name: Demo to PRODUCTION
                trigger: manual
                script:
                     - export APP=fdd.demo.api
                     - export REMOTE=ubuntu@18.195.133.38
                     - export HOST_DIR=/var/www/hosts/fdd-demo-api
                     - git submodule update --init --remote
                     - cd ./src/config && git checkout master && cd ../..
                     - ./deploy.sh

        deploy-production-cf:
            - step:
                name: Test
                script:
                    - echo Test
            - step:
                name: CF To PRODUCTION
                deployment: test
                trigger: manual
                script:
                    - export APP=cffdd.api
                    - export REMOTE=ubuntu@18.195.133.38
                    - export HOST_DIR=/var/www/hosts/cf-api
                    - git submodule update --init --remote
                    - cd ./src/config && git checkout cffdd && cd ../..
                    - ./deploy.sh
